<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEpam8av\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEpam8av/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEpam8av.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEpam8av\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEpam8av\appProdProjectContainer([
    'container.build_hash' => 'Epam8av',
    'container.build_id' => '7385454f',
    'container.build_time' => 1593472274,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEpam8av');
