<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container97vjlqk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container97vjlqk/appProdProjectContainer.php') {
    touch(__DIR__.'/Container97vjlqk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container97vjlqk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container97vjlqk\appProdProjectContainer([
    'container.build_hash' => '97vjlqk',
    'container.build_id' => 'f37ba7b0',
    'container.build_time' => 1593735259,
], __DIR__.\DIRECTORY_SEPARATOR.'Container97vjlqk');
